# Imports

In [2]:
import kagglehub
import os
import shutil

import pandas as pd

from sklearn.model_selection import train_test_split

from autogluon.tabular import TabularDataset, TabularPredictor # type: ignore

/Users/richardcollins/youtube-rainfall-prediction/.venv-autogluon/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

# Download

In [3]:
# Download latest version
path = kagglehub.dataset_download("jsphyg/weather-dataset-rattle-package")

print(f"Path to dataset files: {path}")

# Move datafile to data directory in repo
# Create data directory if it doesn't exist
os.makedirs("../data", exist_ok=True)

# Source and destination paths
source_file = os.path.join(path, "weatherAUS.csv")
dest_file = "../data/weatherAUS.csv"

# Move the file
shutil.copy2(source_file, dest_file)
print(f"Data file moved from {source_file} to {dest_file}")

Path to dataset files: /Users/richardcollins/.cache/kagglehub/datasets/jsphyg/weather-dataset-rattle-package/versions/2
Data file moved from /Users/richardcollins/.cache/kagglehub/datasets/jsphyg/weather-dataset-rattle-package/versions/2/weatherAUS.csv to ../data/weatherAUS.csv

# Explore

## Open and check

In [4]:
df = pd.read_csv("../data/weatherAUS.csv")

print(f"df.shape:")
print(f"{df.shape}")

print(f"df.head():")
print(f"{df.head()}")

df.shape:
(145460, 23)
df.head():
         Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0  2008-12-01   Albury     13.4     22.9       0.6          NaN       NaN
1  2008-12-02   Albury      7.4     25.1       0.0          NaN       NaN
2  2008-12-03   Albury     12.9     25.7       0.0          NaN       NaN
3  2008-12-04   Albury      9.2     28.0       0.0          NaN       NaN
4  2008-12-05   Albury     17.5     32.3       1.0          NaN       NaN

  WindGustDir  WindGustSpeed WindDir9am  ... Humidity9am  Humidity3pm  \
0           W           44.0          W  ...        71.0         22.0
1         WNW           44.0        NNW  ...        44.0         25.0
2         WSW           46.0          W  ...        38.0         30.0
3          NE           24.0         SE  ...        45.0         16.0
4           W           41.0        ENE  ...        82.0         33.0

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1007.7       1007.1       8.0       NaN     16.9     21.8         No
1       1010.6       1007.8       NaN       NaN     17.2     24.3         No
2       1007.6       1008.7       NaN       2.0     21.0     23.2         No
3       1017.6       1012.8       NaN       NaN     18.1     26.5         No
4       1010.8       1006.0       7.0       8.0     17.8     29.7         No

   RainTomorrow
0            No
1            No
2            No
3            No
4            No

[5 rows x 23 columns]

# Drop NaNs

In [5]:
# IMPORTANT: Remove rows where target variable has NaN values
# This must be done AFTER feature preprocessing but BEFORE train-test split
print(f"Dataset shape before removing NaN in target: {df.shape}")
print(f"Number of NaN values in RainTomorrow: {df['RainTomorrow'].isna().sum()}")

# Drop rows where RainTomorrow is NaN - this is crucial for LogisticRegression
df_clean = df.dropna(subset=['RainTomorrow']).copy()

print(f"Dataset shape after removing NaN in target: {df_clean.shape}")
print(f"Number of NaN values in RainTomorrow after cleaning: {df_clean['RainTomorrow'].isna().sum()}")

# Update df to use the cleaned version
df = df_clean

Dataset shape before removing NaN in target: (145460, 23)
Number of NaN values in RainTomorrow: 3267
Dataset shape after removing NaN in target: (142193, 23)
Number of NaN values in RainTomorrow after cleaning: 0

# Declare Target and Features

In [6]:
label = "RainTomorrow"
X = df.drop([label], axis=1)
y = df[label]

# Split train and test

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=37)

### Reconfigure dataset into train and test sets
df_train = pd.concat([X_train, y_train], axis=1)
df_test = pd.concat([X_test, y_test], axis=1)

# Predictor declaration

In [8]:
train_data = TabularDataset(df_train)
predictor = TabularPredictor(label=label).fit(train_data)

No path specified. Models will be saved in: "AutogluonModels/ag-20250722_220101"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.3.1
Python Version:     3.12.11
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 24.5.0: Tue Apr 22 19:54:43 PDT 2025; root:xnu-11417.121.6~2/RELEASE_ARM64_T8132
CPU Count:          10
Memory Avail:       5.43 GB / 16.00 GB (34.0%)
Disk Space Avail:   353.23 GB / 460.43 GB (76.7%)
===================================================
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets. Defaulting to `'medium'`...
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='experimental' : New in v1.2: Pre-trained foundation model + parallel fits. The absolute best accuracy without consideration for inference speed. Does not support GPU.
	presets='best'         : Maximize accuracy. Recommended for most users. Use in competitions and benchmarks.
	presets='high'         : Strong accuracy with fast inference speed.
	presets='good'         : Good accuracy with very fast inference speed.
	presets='medium'       : Fast training time, ideal for initial prototyping.
Warning: Training may take a very long time because `time_limit` was not specified and `train_data` is large (113754 samples, 57.5 MB).
	Consider setting `time_limit` to ensure training finishes within an expected duration or experiment with a small portion of `train_data` to identify an ideal `presets` and `hyperparameters` configuration.
/Users/richardcollins/youtube-rainfall-prediction/.venv-autogluon/lib/python3.12/site-packages/autogluon/common/utils/utils.py:97: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
Beginning AutoGluon training ...
AutoGluon will save models to "/Users/richardcollins/youtube-rainfall-prediction/notebooks/AutogluonModels/ag-20250722_220101"
Train Data Rows:    113754
Train Data Columns: 22
Label Column:       RainTomorrow
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  ['No', 'Yes']
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = Yes, class 0 = No
	Note: For your binary classification, AutoGluon arbitrarily selected which label-value represents positive (Yes) vs negative (No) class.
	To explicitly set the positive_class, either rename classes to 1 and 0, or specify positive_class in Predictor init.
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    5580.51 MB
	Train Data (Original)  Memory Usage: 48.41 MB (0.9% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
		Fitting DatetimeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', [])                      : 16 | ['MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation', 'Sunshine', ...]
		('object', [])                     :  5 | ['Location', 'WindGustDir', 'WindDir9am', 'WindDir3pm', 'RainToday']
		('object', ['datetime_as_object']) :  1 | ['Date']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])             :  5 | ['Location', 'WindGustDir', 'WindDir9am', 'WindDir3pm', 'RainToday']
		('float', [])                : 16 | ['MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation', 'Sunshine', ...]
		('int', ['datetime_as_int']) :  5 | ['Date', 'Date.year', 'Date.month', 'Date.day', 'Date.dayofweek']
	0.2s = Fit runtime
	22 features in original data used to generate 26 features in processed data.
	Train Data (Processed) Memory Usage: 18.77 MB (0.3% of available memory)
Data preprocessing and feature engineering runtime = 0.29s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.02197724915167818, Train Rows: 111254, Val Rows: 2500
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models, fit_strategy="sequential" ...
Fitting model: KNeighborsUnif ...
	0.7528	 = Validation score   (accuracy)
	1.99s	 = Training   runtime
	0.14s	 = Validation runtime
Fitting model: KNeighborsDist ...
	0.7532	 = Validation score   (accuracy)
	0.03s	 = Training   runtime
	0.1s	 = Validation runtime
Fitting model: LightGBMXT ...
	0.852	 = Validation score   (accuracy)
	0.99s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBM ...
	0.8584	 = Validation score   (accuracy)
	1.11s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: RandomForestGini ...
	0.8528	 = Validation score   (accuracy)
	8.77s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: RandomForestEntr ...
	0.852	 = Validation score   (accuracy)
	7.57s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: CatBoost ...
	0.854	 = Validation score   (accuracy)
	13.96s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ...
	0.8472	 = Validation score   (accuracy)
	2.74s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: ExtraTreesEntr ...
	0.8492	 = Validation score   (accuracy)
	2.8s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
	0.8648	 = Validation score   (accuracy)
	34.78s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: XGBoost ...
	0.8616	 = Validation score   (accuracy)
	1.83s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch ...
	0.8636	 = Validation score   (accuracy)
	34.95s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBMLarge ...
	0.8524	 = Validation score   (accuracy)
	0.96s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	Ensemble Weights: {'NeuralNetFastAI': 0.444, 'NeuralNetTorch': 0.444, 'LightGBM': 0.111}
	0.8672	 = Validation score   (accuracy)
	0.04s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 114.24s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 61630.5 rows/s (2500 batch size)
Disabling decision threshold calibration for metric `accuracy` due to having fewer than 10000 rows of validation data for calibration, to avoid overfitting (2500 rows).
	`accuracy` is generally not improved through threshold calibration. Force calibration via specifying `calibrate_decision_threshold=True`.
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/Users/richardcollins/youtube-rainfall-prediction/notebooks/AutogluonModels/ag-20250722_220101")

# Predict

In [9]:
test_data = TabularDataset(df_test)

y_pred = predictor.predict(test_data.drop(columns=[label]))
y_pred.head()

138104    No
32162     No
120242    No
116622    No
56743     No
Name: RainTomorrow, dtype: object

# Evaluate

In [10]:
predictor.evaluate(test_data, silent=True)

{'accuracy': 0.8663455114455502,
 'balanced_accuracy': np.float64(0.7623193269237571),
 'mcc': np.float64(0.5895668394376516),
 'roc_auc': np.float64(0.9052601276179671),
 'f1': 0.6596830513027129,
 'precision': 0.7786937222574508,
 'recall': 0.5722273998136067}

In [11]:
predictor.leaderboard(test_data)

,model,score_test,score_val,eval_metric,pred_time_test,pred_time_val,fit_time,pred_time_test_marginal,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,WeightedEnsemble_L2,0.866346,0.8672,accuracy,0.325832,0.040564,70.881577,0.001208,0.000260,0.040225,2,True,14
1,XGBoost,0.866310,0.8616,accuracy,0.091739,0.010278,1.830335,0.091739,0.010278,1.830335,1,True,11
2,LightGBM,0.865396,0.8584,accuracy,0.075299,0.011821,1.108306,0.075299,0.011821,1.108306,1,True,4
3,NeuralNetFastAI,0.865185,0.8648,accuracy,0.179965,0.017130,34.783215,0.179965,0.017130,34.783215,1,True,10
4,CatBoost,0.862302,0.8540,accuracy,0.047783,0.002736,13.961927,0.047783,0.002736,13.961927,1,True,7
5,NeuralNetTorch,0.860649,0.8636,accuracy,0.069360,0.011353,34.949831,0.069360,0.011353,34.949831,1,True,12
6,LightGBMXT,0.859911,0.8520,accuracy,0.038170,0.006551,0.987128,0.038170,0.006551,0.987128,1,True,3
7,LightGBMLarge,0.858223,0.8524,accuracy,0.036300,0.004559,0.957341,0.036300,0.004559,0.957341,1,True,13
8,RandomForestEntr,0.858153,0.8520,accuracy,0.342439,0.038399,7.573963,0.342439,0.038399,7.573963,1,True,6
9,RandomForestGini,0.857555,0.8528,accuracy,0.356752,0.052575,8.768958,0.356752,0.052575,8.768958,1,True,5
10,ExtraTreesGini,0.854003,0.8472,accuracy,0.417058,0.036243,2.740163,0.417058,0.036243,2.740163,1,True,8
11,ExtraTreesEntr,0.852667,0.8492,accuracy,0.563141,0.038399,2.796514,0.563141,0.038399,2.796514,1,True,9
12,KNeighborsDist,0.744963,0.7532,accuracy,0.939308,0.101773,0.031396,0.939308,0.101773,0.031396,1,True,2
13,KNeighborsUnif,0.744928,0.7528,accuracy,0.908166,0.137485,1.994954,0.908166,0.137485,1.994954,1,True,1

# Predict probabilities

## Merge back into test data

In [ ]:
test_data[["noRainTomorrow_prob", "yesRainTomorrow_prob"]] = predictor.predict_proba(
    test_data
)

test_data.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow,noRainTomorrow_prob,yesRainTomorrow_prob
138104,2014-09-23,AliceSprings,9.0,32.3,0.0,10.2,11.4,NNW,56.0,N,...,1013.6,1009.3,0.0,1.0,23.8,30.8,No,No,0.991548,0.008452
32162,2013-10-07,Sydney,15.8,21.9,0.0,9.8,10.4,SE,52.0,SSW,...,1011.2,1010.8,2.0,2.0,18.3,20.3,No,No,0.903166,0.096834
120242,2016-05-26,PerthAirport,11.5,19.1,2.8,2.0,4.7,SW,37.0,ENE,...,1017.5,1019.2,7.0,7.0,14.8,18.4,Yes,No,0.797599,0.202401
116622,2014-09-23,PearceRAAF,5.6,17.1,0.0,NaN,0.0,NaN,NaN,E,...,1027.2,1025.0,7.0,8.0,14.0,16.5,No,No,0.883169,0.116831
56743,2013-08-27,Ballarat,4.2,16.9,0.0,NaN,NaN,N,41.0,NNE,...,1021.2,1017.8,NaN,NaN,10.5,14.7,No,No,0.800332,0.199668

## Variable Threshold

In [21]:
thresholds = [t / 100.0 for t in range(1, 100)]

for t in thresholds:
    temp_test_data = test_data.copy()
    temp_test_data["predicted_label"] = (
        temp_test_data["yesRainTomorrow_prob"] > t
    ).astype(int)
    temp_test_data["tp"] = (temp_test_data["predicted_label"] == 1) & (
        temp_test_data["RainTomorrow"] == "Yes"
    )
    temp_test_data["fp"] = (temp_test_data["predicted_label"] == 1) & (
        temp_test_data["RainTomorrow"] == "No"
    )
    temp_test_data["fn"] = (temp_test_data["predicted_label"] == 0) & (
        temp_test_data["RainTomorrow"] == "Yes"
    )
    temp_test_data["tn"] = (temp_test_data["predicted_label"] == 0) & (
        temp_test_data["RainTomorrow"] == "No"
    )
    print(
        f"Threshold: {t}, TP: {temp_test_data['tp'].sum()}, FP: {temp_test_data['fp'].sum()}, FN: {temp_test_data['fn'].sum()}, TN: {temp_test_data['tn'].sum()}"
    )

Threshold: 0.01, TP: 6418, FP: 17344, FN: 20, TN: 4657
Threshold: 0.02, TP: 6386, FP: 14929, FN: 52, TN: 7072
Threshold: 0.03, TP: 6341, FP: 13295, FN: 97, TN: 8706
Threshold: 0.04, TP: 6301, FP: 12029, FN: 137, TN: 9972
Threshold: 0.05, TP: 6254, FP: 10959, FN: 184, TN: 11042
Threshold: 0.06, TP: 6201, FP: 10061, FN: 237, TN: 11940
Threshold: 0.07, TP: 6148, FP: 9312, FN: 290, TN: 12689
Threshold: 0.08, TP: 6102, FP: 8674, FN: 336, TN: 13327
Threshold: 0.09, TP: 6035, FP: 8059, FN: 403, TN: 13942
Threshold: 0.1, TP: 5972, FP: 7578, FN: 466, TN: 14423
Threshold: 0.11, TP: 5902, FP: 7133, FN: 536, TN: 14868
Threshold: 0.12, TP: 5834, FP: 6763, FN: 604, TN: 15238
Threshold: 0.13, TP: 5778, FP: 6391, FN: 660, TN: 15610
Threshold: 0.14, TP: 5725, FP: 6047, FN: 713, TN: 15954
Threshold: 0.15, TP: 5685, FP: 5668, FN: 753, TN: 16333
Threshold: 0.16, TP: 5621, FP: 5341, FN: 817, TN: 16660
Threshold: 0.17, TP: 5553, FP: 5087, FN: 885, TN: 16914
Threshold: 0.18, TP: 5509, FP: 4818, FN: 929, TN: 17183
Threshold: 0.19, TP: 5428, FP: 4578, FN: 1010, TN: 17423
Threshold: 0.2, TP: 5375, FP: 4356, FN: 1063, TN: 17645
Threshold: 0.21, TP: 5311, FP: 4131, FN: 1127, TN: 17870
Threshold: 0.22, TP: 5253, FP: 3922, FN: 1185, TN: 18079
Threshold: 0.23, TP: 5196, FP: 3734, FN: 1242, TN: 18267
Threshold: 0.24, TP: 5116, FP: 3556, FN: 1322, TN: 18445
Threshold: 0.25, TP: 5064, FP: 3369, FN: 1374, TN: 18632
Threshold: 0.26, TP: 5007, FP: 3193, FN: 1431, TN: 18808
Threshold: 0.27, TP: 4959, FP: 3052, FN: 1479, TN: 18949
Threshold: 0.28, TP: 4910, FP: 2905, FN: 1528, TN: 19096
Threshold: 0.29, TP: 4860, FP: 2773, FN: 1578, TN: 19228
Threshold: 0.3, TP: 4802, FP: 2652, FN: 1636, TN: 19349
Threshold: 0.31, TP: 4735, FP: 2543, FN: 1703, TN: 19458
Threshold: 0.32, TP: 4676, FP: 2409, FN: 1762, TN: 19592
Threshold: 0.33, TP: 4622, FP: 2312, FN: 1816, TN: 19689
Threshold: 0.34, TP: 4560, FP: 2201, FN: 1878, TN: 19800
Threshold: 0.35, TP: 4501, FP: 2110, FN: 1937, TN: 19891
Threshold: 0.36, TP: 4448, FP: 2008, FN: 1990, TN: 19993
Threshold: 0.37, TP: 4397, FP: 1929, FN: 2041, TN: 20072
Threshold: 0.38, TP: 4337, FP: 1823, FN: 2101, TN: 20178
Threshold: 0.39, TP: 4273, FP: 1734, FN: 2165, TN: 20267
Threshold: 0.4, TP: 4227, FP: 1643, FN: 2211, TN: 20358
Threshold: 0.41, TP: 4171, FP: 1551, FN: 2267, TN: 20450
Threshold: 0.42, TP: 4124, FP: 1491, FN: 2314, TN: 20510
Threshold: 0.43, TP: 4060, FP: 1429, FN: 2378, TN: 20572
Threshold: 0.44, TP: 4013, FP: 1358, FN: 2425, TN: 20643
Threshold: 0.45, TP: 3951, FP: 1312, FN: 2487, TN: 20689
Threshold: 0.46, TP: 3904, FP: 1256, FN: 2534, TN: 20745
Threshold: 0.47, TP: 3857, FP: 1207, FN: 2581, TN: 20794
Threshold: 0.48, TP: 3798, FP: 1149, FN: 2640, TN: 20852
Threshold: 0.49, TP: 3739, FP: 1099, FN: 2699, TN: 20902
Threshold: 0.5, TP: 3684, FP: 1047, FN: 2754, TN: 20954
Threshold: 0.51, TP: 3631, FP: 1003, FN: 2807, TN: 20998
Threshold: 0.52, TP: 3575, FP: 964, FN: 2863, TN: 21037
Threshold: 0.53, TP: 3524, FP: 905, FN: 2914, TN: 21096
Threshold: 0.54, TP: 3449, FP: 860, FN: 2989, TN: 21141
Threshold: 0.55, TP: 3391, FP: 809, FN: 3047, TN: 21192
Threshold: 0.56, TP: 3350, FP: 770, FN: 3088, TN: 21231
Threshold: 0.57, TP: 3290, FP: 733, FN: 3148, TN: 21268
Threshold: 0.58, TP: 3242, FP: 697, FN: 3196, TN: 21304
Threshold: 0.59, TP: 3191, FP: 656, FN: 3247, TN: 21345
Threshold: 0.6, TP: 3139, FP: 616, FN: 3299, TN: 21385
Threshold: 0.61, TP: 3090, FP: 583, FN: 3348, TN: 21418
Threshold: 0.62, TP: 3043, FP: 548, FN: 3395, TN: 21453
Threshold: 0.63, TP: 2984, FP: 509, FN: 3454, TN: 21492
Threshold: 0.64, TP: 2932, FP: 482, FN: 3506, TN: 21519
Threshold: 0.65, TP: 2867, FP: 452, FN: 3571, TN: 21549
Threshold: 0.66, TP: 2812, FP: 422, FN: 3626, TN: 21579
Threshold: 0.67, TP: 2752, FP: 401, FN: 3686, TN: 21600
Threshold: 0.68, TP: 2689, FP: 379, FN: 3749, TN: 21622
Threshold: 0.69, TP: 2639, FP: 365, FN: 3799, TN: 21636
Threshold: 0.7, TP: 2571, FP: 350, FN: 3867, TN: 21651
Threshold: 0.71, TP: 2526, FP: 321, FN: 3912, TN: 21680
Threshold: 0.72, TP: 2462, FP: 296, FN: 3976, TN: 21705
Threshold: 0.73, TP: 2403, FP: 280, FN: 4035, TN: 21721
Threshold: 0.74, TP: 2353, FP: 265, FN: 4085, TN: 21736
Threshold: 0.75, TP: 2304, FP: 245, FN: 4134, TN: 21756
Threshold: 0.76, TP: 2261, FP: 226, FN: 4177, TN: 21775
Threshold: 0.77, TP: 2202, FP: 206, FN: 4236, TN: 21795
Threshold: 0.78, TP: 2138, FP: 189, FN: 4300, TN: 21812
Threshold: 0.79, TP: 2084, FP: 175, FN: 4354, TN: 21826
Threshold: 0.8, TP: 2017, FP: 159, FN: 4421, TN: 21842
Threshold: 0.81, TP: 1951, FP: 143, FN: 4487, TN: 21858
Threshold: 0.82, TP: 1888, FP: 130, FN: 4550, TN: 21871
Threshold: 0.83, TP: 1826, FP: 120, FN: 4612, TN: 21881
Threshold: 0.84, TP: 1765, FP: 111, FN: 4673, TN: 21890
Threshold: 0.85, TP: 1704, FP: 100, FN: 4734, TN: 21901
Threshold: 0.86, TP: 1642, FP: 92, FN: 4796, TN: 21909
Threshold: 0.87, TP: 1571, FP: 89, FN: 4867, TN: 21912
Threshold: 0.88, TP: 1505, FP: 77, FN: 4933, TN: 21924
Threshold: 0.89, TP: 1429, FP: 69, FN: 5009, TN: 21932
Threshold: 0.9, TP: 1337, FP: 54, FN: 5101, TN: 21947
Threshold: 0.91, TP: 1256, FP: 49, FN: 5182, TN: 21952
Threshold: 0.92, TP: 1173, FP: 40, FN: 5265, TN: 21961
Threshold: 0.93, TP: 1076, FP: 32, FN: 5362, TN: 21969
Threshold: 0.94, TP: 958, FP: 25, FN: 5480, TN: 21976
Threshold: 0.95, TP: 849, FP: 18, FN: 5589, TN: 21983
Threshold: 0.96, TP: 710, FP: 13, FN: 5728, TN: 21988
Threshold: 0.97, TP: 570, FP: 7, FN: 5868, TN: 21994
Threshold: 0.98, TP: 401, FP: 2, FN: 6037, TN: 21999
Threshold: 0.99, TP: 192, FP: 0, FN: 6246, TN: 22001